services:
    _defaults:
        autowire: true
        autoconfigure: true

    Cbwar\Bundle\Deluge\:
        resource: '../../*'
        exclude:
            - '../../Exception/'
            - '../../DependencyInjection/'
            - '../../Resources/'
